### ISSUE TITLE
utils\StripeClient - Error

### ISSUE THREAD

**Issue by websnooze** [KevinLu/beatstore#77]
![image](https://user-images.githubusercontent.com/46488156/167742964-4e8eaf90-138b-4110-9f5e-30fc6a36fe3a.png)

**Comment by KevinLu** [comment]
Can you provide more details? What did you do to get those errors? Please give reproduction steps.

**Comment by websnooze** [comment]
I just ran a npm start...

But into client/src/components/utils folder, StripeClient.js is missing

**Comment by KevinLu** [comment]
Ah good catch. I forgot to mention you need to create that file in the README.
To fix it, make the StripeClient.js file with this inside:
```javascript
module.exports = {
    stripePublicKey: "your public key from Stripe here"
}
```

**Comment by websnooze** [comment]
Perfect, that's work !
But I have an other question, do you have a documentation about AWS ? because I don't understand anything about AWS Control panel...

**Comment by KevinLu** [comment]
This project only uses AWS S3, so I suggest learning more about it here https://docs.aws.amazon.com/s3/index.html
