### ISSUE TITLE
AWS s3 - Acces Denied

### ISSUE THREAD

**Issue by websnooze** [KevinLu/beatstore#78]
I looked carefully at the doc, I managed to get the information to connect my Bucket to the application but I have a problem with the permissions I think... The files are uploaded on the Bucket, I see them in my S3 Dashboard but when I click on Upload at the bottom of the page, it grinds and I get this error in the console (it can't read the file from the object address on amazon s3 bucket)
![image](https://user-images.githubusercontent.com/46488156/168503345-5e098444-69e6-4e30-a80b-cfe236ec6cdc.png)
![image](https://user-images.githubusercontent.com/46488156/168503374-c8c13307-bb5f-4454-8417-cb7ba3b631e2.png)

**Comment by websnooze** [comment]
### **UPDATE :**
I've recreated my buckets,
beatstore-public --> Publicly accessible
beatstore-private --> Not.

I just changed `s3PublicBucket` & `s3PrivateBucket` values but not `s3SecretAccessKey` & `s3AccessKeyId`...
Now when I just try to upload a file (mp3/wav), I got this error : 
![image](https://user-images.githubusercontent.com/46488156/168505787-2f07aabe-dc76-41f1-aecc-e1a23d0ff964.png)

**Comment by KevinLu** [comment]
Which service is giving you that error? Is it from AWS or the backend?

**Comment by websnooze** [comment]
okay, fixed ! it was from AWS
