### ISSUE TITLE
No play button + audio visualizer

### ISSUE THREAD

**Issue by websnooze** [KevinLu/beatstore#79]
![image](https://user-images.githubusercontent.com/46488156/169766926-13a36b2c-7c24-4382-aac9-da096a730305.png)
Now everything is working fine, except play beat... I have no play button, no audio visualizer and I can't download public beat version (without error in console)

**Comment by websnooze** [comment]
okay my bad, I have to click on beat image

**Comment by KevinLu** [comment]
Free beat download is not implemented yet, feel free to make a PR if you want to add it :)
I think I removed the audio visualizer because it did not work on mobile, so I still need to figure out a way to get it working again

**Comment by websnooze** [comment]
everything works pretty well, in any case, excellent work! 
I'm getting more and more familiar with Chakra ui
